Update scripts1

diff --git a/Shell/sbornik/scripts1 b/Shell/sbornik/scripts1
--- a/Shell/sbornik/scripts1
+++ b/Shell/sbornik/scripts1
@@ -785,6 +785,7 @@ rows=$(cat "${1}" | sort -t ',' -k 2 | sed -E "s:([1-9]+[0-9]*|0),:\1@:" | sort 
 echo "${rows}" | awk -F '@' '{if (!($2 in min)) {min[$2]=999999} if (min[$2]>$1) {min[$2]=$1}} END {for (curr in min) {print min[curr], curr}}' > "${2}"
 
 ------------------------------------
+
 Зад. 35 2019-SE-01
 Напишете два скрипта (по един за всяка подточка), които четат редове от STDIN.
 Скриптовете трябва да обработват само редовете, които съдържат цели положителни или отрицателни числа;
@@ -846,3 +847,78 @@ done
 
 cat "${fileName1}" | sort -n | head -n 1
 rm -f "${fileName1}"
+
+
+------------------------------------
+
+Зад. 36 2019-SE-02 Напишете шел скрипт, който приема множество параметри. Общ вид на извикване:
+./foo.sh [-n N] FILE1...
+
+В общия случай параметрите се третират като имена на (.log) файлове, които трябва да бъдат обработени от скрипта, със следното изключение: 
+ако първият параметър е стрингът -n, то вторият параметър е число, дефиниращо стойност на променливата N, която ще ползваме в скрипта. 
+Въвеждаме понятието идентификатор на файл(ИДФ), което се състои от името на даден файл без разширението .log 
+За удобство приемаме, че скриптът:
+ • ще бъде извикван с аргументи имена на файлове, винаги завършващи на .log
+ • няма да бъде извикван с аргументи имена на файлове с еднакъв ИДФ.
+ 
+Лог файловете са текстови, като всеки ред има следния формат:
+ • време: timestamp във формат YYYY-MM-DD HH:MM:SS
+ • интервал
+ • данни: поредица от символи с произволна дължина
+ За удобство приемаме, че редовете във всеки файл са сортирани по време възходящо.
+ Примерно съдържание на даден лог файл:
+ 2019-05-05 06:26:54 orthanc rsyslogd: rsyslogd was HUPed
+ 2019-05-06 06:30:32 orthanc rsyslogd: rsyslogd was HUPed
+ 2019-05-06 10:48:29 orthanc kernel: [1725379.728871] Chrome_~dThread[876]: segfault
+
+Скриптът трябва да извежда на STDOUT последните N реда (ако N не е дефинирано - 10 реда) от всеки файл, в следния формат:
+ • timestamp във формат YYYY-MM-DD HH:MM:SS
+ • интервал
+ • ИДФ
+ • интервал
+ • данни
+ Изходът трябва да бъде глобално сортиран по време възходящо.
+
+Solution:
+#!/bin/bash
+
+if [[ "${#}" -eq 0 ]]; then
+    echo "The script cannot be run without arguments"
+    exit 1
+fi
+
+count=10
+if [[ "${1}" = "-n" ]]; then
+    if [[ "${#}" -eq 1 ]]; then
+        echo "-n must be followed by an argument"
+        exit 2
+    fi
+    if ! $(echo "${2}" | grep -q -E "^([1-9]+[0-9]*|0)$"); then
+        echo "-n must be followed b an argument number"
+    fi
+    count="${2}"
+fi
+
+tempFile=$(mktemp)
+
+for filename in ${@}; do
+    if ! $(echo "${filename}" | grep -q -E '.log$'); then
+        continue
+    fi
+    idf=$(basename "${filename}" | rev | cut -c 5- | rev)
+    cat "${filename}" | tail -n "${count}" | awk -v file="${idf}" '
+    {
+        for (i=1;i<=NF;i++) {
+            printf "%s ", $i
+            if (i == 2) {
+                printf "%s ", file
+            }
+        }
+    }
+
+    {printf "\n"}' >> "${tempFile}"
+
+done
+
+cat "${tempFile}" | sort -t ' ' -k 2,2 -V
+rm -f "${tempFile}"
